version: "3"

services:
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"

  app:
    container_name: app
    build: .
    command: yarn dev
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - MONGO_URL=database
    volumes:
      - ".:/usr/app"
